### ISSUE TITLE
About connect options

### ISSUE THREAD

**Issue by ggggamer** [sinacloud/nodejs-getting-started#1]
When print all env variables, I didn't find `MYSQL_HOST`, just `SAE_MYSQL_HOST_M` and `SAE_MYSQL_HOST_S`.

An other quetion is, the best practices is use `ACCESSKEY` and `SECRETKEY` or `SAE_MYSQL_USER` and `SAE_MYSQL_PASS`.

``` js
var connection = mysql.createConnection({
    host     : process.env.MYSQL_HOST,// SAE_MYSQL_HOST_M or SAE_MYSQL_HOST_S
    port     : process.env.SAE_MYSQL_PORT,
    user     : process.env.SAE_MYSQL_USER,
    password : process.env.SAE_MYSQL_PASS,
    database : process.env.SAE_MYSQL_DB,
});
```

**Comment by chanfung032** [comment]
你好，因为服务还在测试中，这个是之前的设置，现在已经修改成线上的了，已经运行的实例需要重新部署才能生效。
